const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
class Element{constructor(tag){this.tag=tag;this.children=[];this.handlers={}}createEl(tag,options={}){const e=new Element(tag);e.text=options.text;e.attr=options.attr;this.children.push(e);return e}createDiv(options={}){return this.createEl('div',options)}createSpan(options={}){return this.createEl('span',options)}empty(){this.children=[]}addEventListener(name,fn){this.handlers[name]=fn}addClass(){} }
class Modal{constructor(app){this.app=app;this.contentEl=new Element('root')}open(){this.onOpen?.()}close(){this.onClose?.()}}
function load(){const c=vm.createContext({module:{exports:{}},require(){return {Plugin:class{},PluginSettingTab:class{},Modal,TFile:class{},Notice:class{},requestUrl:async request=>{c.request=request;return c.response||{status:200,json:{}}}}},console,URL,Set,Map,Date,TextEncoder,TextDecoder,Uint8Array,crypto:webcrypto,btoa,atob,window:{},document:{}});vm.runInContext(fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8'),c);const helpers=vm.runInContext('({portableConfig,encryptProfile,decryptProfile,validatePortableConfig,ShareManagerModal,migrateSettings})',c);return {c,helpers,p:new c.module.exports()};}
const fixture={serverUrl:'https://share.example.test',apiToken:'fixture-api-token',alistPublicUrl:'https://files.example.test',alistUsername:'fixture-user',alistPassword:'fixture-password',alistToken:'old-session',alistAutoUpload:true,alistDeleteRemoteOnNoteDelete:false,shares:{a:{shareId:'kept',editToken:'local-only-edit'}},attachmentAssets:{a:[{remotePath:'/files/keep'}]},pendingUploads:{a:{remotePath:'/files/pending'}}};
test('encrypted profile round-trips Unicode; no credentials or runtime state leak',async()=>{const {helpers:h}=load();const config=h.portableConfig(fixture);const text=await h.encryptProfile(config,'测试密码abcdefgh','0.5.9');assert(!text.includes(fixture.apiToken));assert(!text.includes(fixture.alistPassword));assert(!text.includes(fixture.serverUrl));assert(!text.includes('local-only-edit'));assert(!('shares'in config));assert(!('attachmentAssets'in config));assert(!('pendingUploads'in config));assert(!('alistToken'in config));const decoded=await h.decryptProfile(text,'测试密码abcdefgh');assert.equal(decoded.apiToken,fixture.apiToken);assert(!('alistPassword'in decoded));});
test('wrong passwords, tampering, unsupported schema and task injection are rejected',async()=>{const {helpers:h}=load();const text=await h.encryptProfile(h.portableConfig(fixture),'abcdefgh','0.5.9');await assert.rejects(()=>h.decryptProfile(text,'incorrect-password'));const obj=JSON.parse(text);obj.ciphertext=(obj.ciphertext[0]==='A'?'B':'A')+obj.ciphertext.slice(1);await assert.rejects(()=>h.decryptProfile(JSON.stringify(obj),'abcdefgh'));obj.schemaVersion=99;await assert.rejects(()=>h.decryptProfile(JSON.stringify(obj),'abcdefgh'));assert.throws(()=>h.validatePortableConfig({shares:{}}));assert.throws(()=>h.validatePortableConfig(JSON.parse('{"__proto__":{"bad":true}}')));assert.throws(()=>h.validatePortableConfig({serverUrl:'javascript:alert(1)'}));await assert.rejects(()=>h.decryptProfile('x'.repeat(262145),'abcdefgh'));});
test('import preserves identity/attachment jobs; backup is encrypted and saves can roll back',async()=>{const {helpers:h,p}=load();p.settings={...fixture};p.manifest={id:'private-share',version:'0.5.9'};let backup; p.app={vault:{configDir:'.obsidian',adapter:{write:async(_file,data)=>backup=data}}};p.saveData=async()=>{};const shares=p.settings.shares,assets=p.settings.attachmentAssets,pending=p.settings.pendingUploads;const config=h.portableConfig(fixture);await p.applyPortableConfig(config,'abcdefgh');assert.equal(p.settings.shares,shares);assert.equal(p.settings.attachmentAssets,assets);assert.equal(p.settings.pendingUploads,pending);assert.equal(p.settings.serverUrl,fixture.serverUrl);assert(!backup.includes(fixture.apiToken));const restored=await h.decryptProfile(backup,'abcdefgh');assert(!('alistAutoUpload'in restored));p.saveData=async()=>{throw Error('disk full')};const before=p.settings;await assert.rejects(()=>p.applyPortableConfig(config,'abcdefgh'));assert.equal(p.settings,before);assert.equal(p.configTransferRunning,false);});
test('active jobs and backend changes cannot import over historical ownership',async()=>{const {helpers:h,p}=load();p.settings={...fixture};p.backupJobs=new Map([['x',Promise.resolve()]]);await assert.rejects(()=>p.applyPortableConfig(h.portableConfig(fixture),'abcdefgh'));p.backupJobs.clear();const changed=h.portableConfig(fixture);changed.serverUrl='https://different.example.test';await assert.rejects(()=>p.applyPortableConfig(changed,'abcdefgh'));});
test('expiry uses metadata-only PATCH with claimed management token',async()=>{const {p}=load();p.settings={shares:{note:{shareId:'same',editToken:'stable'}}};p.claimManageShareForPath=async()=>p.settings.shares.note;p.saveData=async()=>{};let request;p.api=async(...args)=>{request=args;return {expiresAt:null}};await p.changeShareExpiry('note',p.settings.shares.note,null);assert.equal(request[0],'/api/share/same/expiry');assert.equal(request[1],'PATCH');assert.equal(Object.keys(request[2]).join(','),'expiresAt');assert.equal(request[3],'stable');assert.equal(p.settings.shares.note.expiresAt,null);});
test('all manager rows expose expiry and deletion even without discussion or local note',()=>{const {helpers:h,p}=load();p.settings={shares:{missing:{title:'Remote note',shareId:'same',discussionEnabled:false}}};const app={vault:{getAbstractFileByPath:()=>null}};const modal=new h.ShareManagerModal(app,p);modal.render();function texts(e){return [e.text,...e.children.flatMap(texts)].filter(Boolean)}const rendered=texts(modal.contentEl);assert(rendered.includes('修改到期时间'));assert(rendered.includes('删除分享'));assert(!rendered.includes('客户链接'));});

test('migration retains attachment ownership, shares and resumable jobs while removing obsolete settings',()=>{const {helpers:h}=load();const legacy={serverUrl:fixture.serverUrl,apiToken:fixture.apiToken,shares:fixture.shares,alistAssets:fixture.attachmentAssets,pendingAListUploads:fixture.pendingUploads,localUploadUrl:'http://10.0.0.1',alistPassword:'unused',alistAutoUpload:false};const s=h.migrateSettings(legacy);assert.equal(s.shares,fixture.shares);assert.equal(s.attachmentAssets,fixture.attachmentAssets);assert.equal(s.pendingUploads,fixture.pendingUploads);assert.equal(Object.keys(s).sort().join(','),'apiToken,attachmentAssets,pendingUploadedShareRefresh,pendingUploads,serverUrl,shares');assert.equal(h.migrateSettings(s).attachmentAssets,s.attachmentAssets);const portable=h.validatePortableConfig({serverUrl:fixture.serverUrl,apiToken:fixture.apiToken,alistPassword:'ignored',localUploadUrl:'http://10.0.0.1'});assert.equal(Object.keys(portable).sort().join(','),'apiToken,serverUrl');});
