const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
class File{constructor(path){this.path=path;this.name=path.split('/').pop();this.extension=this.name.split('.').pop();this.stat={mtime:1,size:3};}}
function load(mobile=false,request=null){const c=vm.createContext({module:{exports:{}},require(n){return n==='obsidian'?{Platform:{isMobile:mobile},Plugin:class{},PluginSettingTab:class{},Setting:class{},Modal:class{},TFile:File,Notice:class{},requestUrl:request||async function(){return {status:206,headers:{'content-range':'bytes 0-0/3'}}}}:require(n)},console,URL,Date,Map,Set,Buffer,Uint8Array,ArrayBuffer,setTimeout,clearTimeout,window:{setTimeout,clearTimeout}});vm.runInContext(fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8'),c);const p=new c.module.exports();p.settings={serverUrl:'https://share.example.test',apiToken:'fixture',alistAssets:{},shares:{}};p.saveData=async()=>{};p.getAListToken=()=>assert.fail('new uploads must not use AList');return p;}
function setup(){const p=load(),file=new File('x.mp3'),key='private-share-direct/'+'a'.repeat(32)+'/attachment.mp3';p.app={vault:{readBinary:async()=>new Uint8Array([1,2,3]).buffer,adapter:{stat:async()=>file.stat}}};p.api=async route=>{assert.equal(route,'/api/media/upload-ticket');return {base:'https://files.example.test',key,remotePath:'/Obsidian/'+key,chunk:8*1024**2,ticket:'fixture',expiresAt:Date.now()+3600000};};return {p,file,key};}
test('mobile refuses uploads before requesting tickets or reading bytes',async()=>{const p=load(true);p.app={vault:{readBinary:()=>assert.fail('mobile bytes')}};assert.equal(await p.desktopUploadAvailable(),false);assert.equal(await p.scanDesktopAttachments(),false);await assert.rejects(()=>p.uploadFileToVPS(new File('x.mp3')));});
test('images stay local and never obtain upload tickets',async()=>{const p=load();p.api=()=>assert.fail('image ticket');await assert.rejects(()=>p.uploadFileToVPS(new File('image.png')));});
test('direct upload works without AList configuration and returns VPS ownership',async()=>{const {p,file,key}=setup();let parts=0;p.directRequest=async(_base,route,_ticket,_method,body)=>{if(route.endsWith('status'))return {done:false,parts:[]};if(route.endsWith('start'))return {session:'fixture'};if(route.endsWith('part')){parts++;return {part:{partNumber:1,etag:'hash'}};}return {done:true,key,size:3,code:'abcdefghijklmnop'};};const a=await p.uploadFileToVPS(file);assert.equal(parts,1);assert.equal(a.backend,'vps');assert.equal(a.publicUrl,'https://files.example.test/m/abcdefghijklmnop');});
test('same attachment across notes uses one in-flight upload',async()=>{const p=load(),file=new File('x.pdf');let count=0,release;const gate=new Promise(r=>release=r);p.performVPSUpload=async()=>{count++;await gate;return {};};const a=p.uploadFileToVPS(file),b=p.uploadFileToVPS(file);release();await Promise.all([a,b]);assert.equal(count,1);});
test('resume trusts server-confirmed chunks instead of stale client progress',async()=>{const {p,file,key}=setup();p.directRequest=async(_base,route)=>{if(route.endsWith('status'))return {done:false,parts:[{partNumber:1,etag:'hash'}]};if(route.endsWith('start'))return {session:'fixture'};assert(!route.endsWith('part'));return {done:true,key,size:3,code:'abcdefghijklmnop'};};await p.uploadFileToVPS(file);});
test('deleted source never sends a chunk or publishes a link',async()=>{const {p,file}=setup();p.app.vault.adapter.stat=async()=>null;p.directRequest=async(_base,route)=>{if(route.endsWith('status'))return {done:false,parts:[]};if(route.endsWith('start'))return {session:'fixture'};assert.fail('deleted source must not upload');};await assert.rejects(()=>p.uploadFileToVPS(file),/删除|改变/);});
test('missing configuration leaves local attachments unchanged',async()=>{const p=load();p.settings.serverUrl='';p.app={vault:{readBinary:()=>assert.fail('bytes')}};assert.equal(await p.scanDesktopAttachments(),false);});
test('pending direct deletion uses reference checked API and retains failures',async()=>{const p=load();p.settings.alistAssets.a=[{backend:'vps',remotePath:'/Obsidian/private-share-direct/'+ 'a'.repeat(32)+'/attachment.mp3',pendingDelete:true,deleteReason:'link'}];p.verifyAListReferences=async()=>new Set();p.collectVaultMediaUrls=async()=>[];p.api=async()=>{throw Error('offline')};await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a[0].cleanupStatus,'retry');p.api=async route=>{assert.equal(route,'/api/media/direct-delete');return {ok:true};};await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a,undefined);});

test('desktop discovers already synchronized older files despite cutover exclusions',async()=>{const p=load();p.settings.directCutoverComplete=true;p.settings.directCutoverAt=Date.now();p.settings.localOnlyAttachmentPaths={'old.pdf':true};const target=new File('old.pdf'),note=new File('phone.md');let calls=0;p.desktopUploadAvailable=async()=>true;p.app={vault:{getMarkdownFiles:()=>[note],read:async()=> '![[old.pdf]]\n[old](old.pdf)\n[remote](https://example.test/a.png)'},metadataCache:{getFirstLinkpathDest:raw=>raw==='old.pdf'?target:null}};p.uploadCurrentNoteAttachmentsToAList=async(file,options)=>{assert.equal(file,note);assert.equal(options.automatic,true);calls++;return true;};p.retryUploadedShareRefresh=async()=>{};assert.equal(await p.scanDesktopAttachments(),true);assert.equal(calls,1);});
test('mobile non-image share payload retains local note links with placeholders',async()=>{const p=load(true);const target=new File('phone.pdf'),note=new File('phone.md'),text='![[phone.pdf]]\n[图片](phone.pdf)';p.app={metadataCache:{getFirstLinkpathDest:()=>target},vault:{read:async()=>text,readBinary:()=>assert.fail('mobile must not read bytes')}};const {payload}=await p.preparePayload(note,{},null);assert.equal(payload.attachments.length,0);assert(payload.markdown.includes('等待电脑上传'));assert.equal(await p.app.vault.read(note),text);});
test('automatic refresh preserves share controls and never creates a missing share',async()=>{const p=load();const note=new File('note.md');p.settings.pendingUploadedShareRefresh={'note.md':true};p.settings.shares['note.md']={shareId:'same',editToken:'stable',passwordProtected:true,discussionEnabled:true};p.app={vault:{getAbstractFileByPath:()=>note}};let updated=0;p.claimManageShareForPath=async()=>p.settings.shares['note.md'];p.preparePayload=async(f,options,existing,run)=>{assert.equal(options.expiryMode,'keep');assert.equal(options.passwordProtected,true);assert.equal(options.discussionEnabled,true);assert.equal(run.skipUpload,true);return {payload:{markdown:'uploaded'}};};p.api=async(route,method,body,token)=>{assert.equal(route,'/api/update/same');assert.equal(token,'stable');updated++;};await p.retryUploadedShareRefresh();assert.equal(updated,1);assert.equal(Object.keys(p.settings.pendingUploadedShareRefresh).length,0);p.settings.pendingUploadedShareRefresh={'note.md':true};p.claimManageShareForPath=async()=>null;await p.retryUploadedShareRefresh();assert.equal(updated,1);assert.equal(Object.keys(p.settings.pendingUploadedShareRefresh).length,0);});
test('failed share refresh retains marker for a later retry',async()=>{const p=load();const note=new File('note.md');p.settings.pendingUploadedShareRefresh={'note.md':true};p.app={vault:{getAbstractFileByPath:()=>note}};p.claimManageShareForPath=async()=>{throw Error('offline')};await p.retryUploadedShareRefresh();assert.equal(p.settings.pendingUploadedShareRefresh['note.md'],true);});

test('desktop media ticket prefers local share service without touching AList',async()=>{const urls=[];const p=load(false,async req=>{urls.push(req.url);return {status:200,json:{ticket:'fixture'}}});p.settings.localUploadUrl='http://10.10.10.1:8090';assert.equal((await p.api('/api/media/upload-ticket','POST',{})).ticket,'fixture');assert.deepEqual(urls,['http://10.10.10.1:8090/api/media/upload-ticket']);});
test('unavailable local media API falls back to public service',async()=>{const urls=[];const p=load(false,async req=>{urls.push(req.url);if(req.url.startsWith('http:'))throw Error('offline');return {status:200,json:{ok:true}}});p.settings.localUploadUrl='http://10.10.10.1:8090';await p.api('/api/media/references','POST',{urls:[]});assert.equal(urls[1],'https://share.example.test/api/media/references');});
test('mobile never sends management credentials to optional LAN service',async()=>{const urls=[];const p=load(true,async req=>{urls.push(req.url);return {status:200,json:{ok:true}}});p.settings.localUploadUrl='http://10.10.10.1:8090';await p.api('/api/media/references','POST',{urls:[]});assert.equal(urls[0],'https://share.example.test/api/media/references');});
