const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
class File {constructor(path){this.path=path;this.extension='md';}}
function plugin(){const context={module:{exports:{}},require(){return {Plugin:class{},PluginSettingTab:class{},Modal:class{},TFile:File,Notice:class{},requestUrl:async()=>context.response};},console,URL,Set,Map,Date,window:{},document:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8'),context);const p=new context.module.exports();p.settings={shares:{},alistAssets:{}};p.saveData=async()=>{};return {p,context};}
test('already missing share unshares successfully',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'old'};p.api=async()=>{const e=Error('share not found');e.status=404;throw e;};assert.equal(await p.unshareByPath('a',false),true);assert.equal(p.settings.shares.a,undefined);});
test('passive sync uses read endpoint and preserves management token',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'one',editToken:'keep'};p.api=async(u,m)=>{assert.equal(m,'GET');assert(u.includes('resolve'));return {shareId:'one'};};await p.syncShareStateForPath('a');assert.equal(p.settings.shares.a.editToken,'keep');});
test('malformed sync never clears local state; newest duplicate wins',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'keep'};p.api=async()=>({});await p.syncAllSharesFromServer();assert.equal(p.settings.shares.a.shareId,'keep');p.api=async()=>({shares:[{sourcePath:'a',shareId:'new'},{sourcePath:'a',shareId:'old'}]});await p.syncAllSharesFromServer();assert.equal(p.settings.shares.a.shareId,'new');});
test('pending cleanup protects copied URLs outside bookkeeping',async()=>{const {p}=plugin();p.settings.alistAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.app={vault:{getMarkdownFiles(){return [new File('copied.md')];},async read(){return '<video src="https://media.example.com/m/abcdefghijklmnop"></video>';}}};p.api=async(u,m,b)=>{assert(b.urls[0].includes('/m/'));return {remotePaths:['/Obsidian/x'],unresolved:false};};p.deleteAListRemoteAsset=async()=>assert.fail('must not delete');await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a.length,1);});
test('failed cleanup keeps record then successful retry removes it',async()=>{const {p}=plugin();p.settings.alistAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.verifyAListReferences=async()=>new Set();p.getAListToken=async()=>'';p.deleteAListRemoteAsset=async()=>{throw Error('network');};await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a[0].cleanupStatus,'retry');p.deleteAListRemoteAsset=async()=>{};await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a,undefined);});
test('unresolved reference lookup fails closed',async()=>{const {p}=plugin();p.settings.alistAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.verifyAListReferences=async()=>{throw Error('unresolved');};p.deleteAListRemoteAsset=async()=>assert.fail('must not delete');await p.retryAListCleanup();assert.equal(p.settings.alistAssets.a.length,1);});

test('legacy media URLs are rejected before rewriting the note',async()=>{const {p,context}=plugin();p.settings.serverUrl='https://share.example.com';p.settings.apiToken='test-only';context.response={status:200,json:{url:'https://share.example.com/media?u=old'}};await assert.rejects(()=>p.getMediaProxyUrl('', '/Obsidian/x'));context.response={status:200,json:{url:'https://media.example.com/m/abcdefghijklmnop'}};assert.equal(await p.getMediaProxyUrl('', '/Obsidian/x'),'https://media.example.com/m/abcdefghijklmnop');});
test('upload rewrite preserves edits made while upload is running',async()=>{const {p}=plugin();const note=new File('note.md'),target=new File('image.png');target.extension='png';target.name='image.png';let latest='![[image.png]]';p.validateAListSettings=()=>({});p.getAListToken=async()=>'';p.uploadFileToAList=async()=>{latest+='\nNew text typed during upload';return {remotePath:'/Obsidian/x',publicUrl:'https://media.example.com/m/abcdefghijklmnop'};};p.app={metadataCache:{getFirstLinkpathDest:()=>target},vault:{read:async()=>latest,process:async(f,update)=>{latest=update(latest);}}};assert.equal(await p.uploadCurrentNoteAttachmentsToAList(note),true);assert(latest.includes('New text typed during upload'));assert(latest.includes('/m/abcdefghijklmnop'));assert(!latest.includes('![[image.png]]'));});

test('concurrent manual and automatic uploads share one operation',async()=>{const {p}=plugin();let calls=0,finish;const pending=new Promise(r=>finish=r);p.performAListUpload=async()=>{calls++;await pending;return true;};const f=new File('note.md');const a=p.uploadCurrentNoteAttachmentsToAList(f),b=p.uploadCurrentNoteAttachmentsToAList(f);finish();await Promise.all([a,b]);assert.equal(calls,1);assert.equal(p.alistUploadJobs.size,0);});
test('note deletion queues cleanup only after confirmation',async()=>{const {p}=plugin();p.settings.alistAssets.a=[{remotePath:'/Obsidian/x'}];p.confirmRemoteCleanup=async()=>false;p.retryAListCleanup=async()=>{};await p.handleDeletedNoteAListAssets('a');assert(!p.settings.alistAssets.a[0].pendingDelete);p.confirmRemoteCleanup=async()=>true;await p.handleDeletedNoteAListAssets('a');assert.equal(p.settings.alistAssets.a[0].pendingDelete,true);assert.equal(p.settings.alistAssets.a[0].deleteReason,'note');});
