const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
class File {constructor(path){this.path=path;this.extension='md';}}
function plugin(){const context={module:{exports:{}},require(){return {Plugin:class{},PluginSettingTab:class{},Modal:class{},TFile:File,Notice:class{},requestUrl:async()=>context.response};},console,URL,Set,Map,Date,window:{},document:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8'),context);const p=new context.module.exports();p.settings={shares:{},attachmentAssets:{}};p.saveData=async()=>{};return {p,context};}
test('already missing share unshares successfully',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'old'};p.api=async(u,m,body)=>{assert.equal(u,'/api/share/unpublish');assert.equal(body.sourcePath,'a');return {ok:true,removed:0};};assert.equal(await p.unshareByPath('a',false),true);assert.equal(p.settings.shares.a,undefined);});
test('passive sync uses read endpoint and preserves management token',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'one',editToken:'keep'};p.api=async(u,m)=>{assert.equal(m,'GET');assert(u.includes('resolve'));return {shareId:'one'};};await p.syncShareStateForPath('a');assert.equal(p.settings.shares.a.editToken,'keep');});
test('malformed sync never clears local state; newest duplicate wins',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'keep'};p.api=async()=>({});await p.syncAllSharesFromServer();assert.equal(p.settings.shares.a.shareId,'keep');p.api=async()=>({shares:[{sourcePath:'a',shareId:'new'},{sourcePath:'a',shareId:'old'}]});await p.syncAllSharesFromServer();assert.equal(p.settings.shares.a.shareId,'new');});
test('pending cleanup protects copied URLs outside bookkeeping',async()=>{const {p}=plugin();p.settings.attachmentAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.app={vault:{getMarkdownFiles(){return [new File('copied.md')];},async read(){return '<video src="https://media.example.com/m/abcdefghijklmnop"></video>';}}};p.api=async(u,m,b)=>{assert(b.urls[0].includes('/m/'));return {remotePaths:['/Obsidian/x'],unresolved:false};};p.deleteAListRemoteAsset=async()=>assert.fail('must not delete');await p.retryAttachmentCleanup({manual:true});assert.equal(p.settings.attachmentAssets.a.length,1);});
test('failed cleanup keeps record then successful retry removes it',async()=>{const {p}=plugin();p.settings.attachmentAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.verifyAttachmentReferences=async()=>new Set();p.collectVaultMediaUrls=async()=>[];p.api=async()=>{throw Error('network');};await p.retryAttachmentCleanup({manual:true});assert.equal(p.settings.attachmentAssets.a[0].cleanupStatus,'retry');p.api=async()=>({ok:true});await p.retryAttachmentCleanup({manual:true});assert.equal(p.settings.attachmentAssets.a,undefined);});
test('unresolved reference lookup fails closed',async()=>{const {p}=plugin();p.settings.attachmentAssets.a=[{remotePath:'/Obsidian/x',pendingDelete:true,deleteReason:'link'}];p.verifyAttachmentReferences=async()=>{throw Error('unresolved');};p.deleteAListRemoteAsset=async()=>assert.fail('must not delete');await p.retryAttachmentCleanup({manual:true});assert.equal(p.settings.attachmentAssets.a.length,1);});

test('backup preserves local references and edits made while upload is running',async()=>{const {p}=plugin();const note=new File('note.md'),target=new File('document.pdf');target.extension='pdf';target.name='document.pdf';target.stat={mtime:2,size:1};p.settings.directCutoverComplete=true;p.settings.directCutoverAt=1;p.settings.serverUrl='https://share.example.test';p.settings.apiToken='fixture';let latest='![[document.pdf]]';p.validateAListSettings=()=>({});p.getAListToken=async()=>'';p.desktopUploadAvailable=async()=>true;p.uploadFileToVPS=async()=>{latest+='\nNew text typed during upload';return {remotePath:'/Obsidian/x',publicUrl:'https://media.example.com/m/abcdefghijklmnop'};};p.app={metadataCache:{getFirstLinkpathDest:()=>target},vault:{read:async()=>latest,process:async(f,update)=>{latest=update(latest);}}};assert.equal(await p.backupCurrentNote(note),true);assert(latest.includes('New text typed during upload'));assert(!latest.includes('/m/abcdefghijklmnop'));assert(latest.includes('![[document.pdf]]'));assert.equal(p.settings.attachmentAssets['note.md'][0].publicUrl,'https://media.example.com/m/abcdefghijklmnop');});

test('concurrent manual and automatic uploads share one operation',async()=>{const {p}=plugin();let calls=0,finish;const pending=new Promise(r=>finish=r);p.backupNoteAttachments=async()=>{calls++;await pending;return true;};const f=new File('note.md');const a=p.backupCurrentNote(f),b=p.backupCurrentNote(f);finish();await Promise.all([a,b]);assert.equal(calls,1);assert.equal(p.backupJobs.size,0);});
test('note deletion only queues cleanup and never deletes automatically',async()=>{const {p}=plugin();p.settings.attachmentAssets.a=[{remotePath:'/Obsidian/a'}];p.api=()=>assert.fail('deletion must be manual');await p.queueDeletedNoteAttachments('a');assert.equal(p.settings.attachmentAssets.a[0].pendingDelete,true);assert.equal(p.settings.attachmentAssets.a[0].deleteReason,'note');});

test('unverified cancellation never clears local state',async()=>{const {p}=plugin();p.settings.shares.a={shareId:'keep'};p.api=async()=>{throw Error('network');};assert.equal(await p.unshareByPath('a',false),false);assert.equal(p.settings.shares.a.shareId,'keep');});
