const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
class Element{constructor(){this.children=[];}createEl(_tag,o={}){const e=new Element();e.text=o.text;this.children.push(e);return e;}createDiv(){return this.createEl('div');}empty(){this.children=[];}}
const rows=[],buttons=[];
class Setting{constructor(el){this.row={};rows.push(this.row);}setName(v){this.row.name=v;return this;}setDesc(v){this.row.desc=v;return this;}addText(fn){this.row.input=true;const t={inputEl:{},setPlaceholder(){return this},setValue(){return this},onChange(fn){this.change=fn;return this}};fn(t);return this;}addButton(fn){const b={setButtonText(v){this.text=v;return this},setWarning(){return this},setDisabled(v){this.disabled=v;return this},onClick(fn){this.click=fn;return this}};buttons.push(b);fn(b);return this;}}
class Modal{constructor(app){this.app=app;this.contentEl=new Element();}open(){this.onOpen?.();}close(){this.onClose?.();}}
function load(){rows.length=0;buttons.length=0;const c=vm.createContext({module:{exports:{}},require(){return {Platform:{isMobile:false},Plugin:class{},PluginSettingTab:class{},Setting,Modal,TFile:class{},Notice:class{}}},console,URL,Set,Map,Date});vm.runInContext(fs.readFileSync(path.join(__dirname,'..','main.js'),'utf8'),c);return {p:new c.module.exports(),...vm.runInContext('({PrivateShareSettingTab,AttachmentCleanupModal})',c)};}
test('settings show exactly two editable connection fields and no LAN, AList or automatic deletion toggles',()=>{const {p,PrivateShareSettingTab}=load();p.settings={serverUrl:'https://share.example.test',apiToken:'fixture'};const tab=new PrivateShareSettingTab({},p);tab.containerEl=new Element();tab.display();assert.deepEqual(rows.filter(r=>r.input).map(r=>r.name),['分享地址','连接密钥']);assert(!rows.some(r=>/AList|局域网|Token|自动删除/.test(r.name)));assert(buttons.some(b=>b.text==='检查并重试'));assert(buttons.some(b=>b.text==='检查可清理附件'));});
test('manual cleanup cancel never mutates pending state or deletes files',async()=>{const {p,AttachmentCleanupModal}=load(),asset={remotePath:'/Obsidian/x.pdf'};p.api=()=>assert.fail('cancel must not delete');new AttachmentCleanupModal({},p,[{notePath:'note.md',asset}]).open();await buttons.find(b=>b.text==='取消').click();assert(!asset.pendingDelete);});
test('confirmed cleanup enables manual verification and keeps referenced records',async()=>{const {p,AttachmentCleanupModal}=load(),asset={remotePath:'/Obsidian/x.pdf'};p.settings={attachmentAssets:{'note.md':[asset]}};p.saveData=async()=>{};let count=0;p.retryAttachmentCleanup=async options=>{assert.equal(options.manual,true);assert.equal(asset.pendingDelete,true);count++;};new AttachmentCleanupModal({},p,[{notePath:'note.md',asset}]).open();await buttons.find(b=>b.text==='确认检查并清理').click();assert.equal(count,1);assert.equal(p.settings.attachmentAssets['note.md'][0],asset);});
